// Generated by https://quicktype.io

/**
 * Tipos de Dato que deben tener la informacion solicitada de la petición
 */

export interface InfoUsers {
    page:        number;
    per_page:    number;
    total:       number;
    total_pages: number;
    data:        UserInfo[];
    support:     Support;
}

export interface UserInfo {
    id:         number;
    email:      string;
    first_name: string;
    last_name:  string;
    avatar:     string;
}

export interface Support {
    url:  string;
    text: string;
}


